site_name: Dive into Keras Source Code
theme:
  name: material
  palette:
      scheme: default
docs_dir: keras
repo_url: https://github.com/haifeng-jin/keras-source
site_url: https://haifeng-jin.github.io/keras-source
edit_uri: ""
site_description: "Dive into Keras Source Code"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction: index.md
  - 1. Modeling API overview: 01-modeling-api-overview.md
  - 2. The Layer class: 02-the-layer-class.md
  - 3. The Model class: 03-the-model-class.md
  - 4. The Functional class: 04-the-functional-class.md
  - 5. The Sequential class: 05-the-sequential-class.md
